variable "byop_project_id" {
  type        = string
  description = "The BYOP Google Cloud Project ID where Google SecOps metrics are stored and Alert Policies are deployed."
}

variable "orchestration_project_id" {
  type        = string
  description = "The GCP Project ID where the serverless orchestration resources (GCS, Secrets, Cloud Run Function, Scheduler) are deployed."
}

variable "region" {
  type        = string
  description = "GCP Region for the serverless and storage resources."
  default     = "us-central1"
}

variable "contract_terms_json" {
  type        = string
  description = "Serialized JSON string of the multi-year contract term list."
  default     = "[]"
}

variable "monitors" {
  type = map(object({
    log_type              = string
    alert_window_seconds  = number
    alert_window_human    = optional(string)
    volume_threshold      = number
    latency_p95_seconds   = optional(number, 1800)
    latency_p95_human     = optional(string, "30m")
  }))
  description = "Dynamic list of active log sources and their respective SLA windows, generated by the profiler."
  default     = {}
}

variable "webhook_url" {
  type        = string
  description = "Optional Webhook URL to populate in Secret Manager if not pre-created."
  default     = ""
}

variable "create_webhook_secret" {
  type        = bool
  description = "Set to true if Secret Manager secret secops-soar-webhook-url should be created by Terraform."
  default     = false
}

variable "host_monitors" {
  type = map(object({
    host_name            = string
    alert_window_seconds = number
    alert_window_human   = optional(string)
    ignore               = optional(bool, false)
  }))
  description = "Dynamic list of monitored endpoint hosts and overrides."
  default     = {}
}
