variable "project_id" {
  type        = string
  description = "The BYOP Google Cloud Project ID where Google SecOps metrics are stored."
}

variable "soar_webhook_url" {
  type        = string
  description = "The target Webhook URL for Google SecOps SOAR."
}

variable "monitors" {
  type = map(object({
    log_type              = string
    alert_window_seconds  = number
    volume_threshold      = number
  }))
  description = "Dynamic list of active log sources and their respective SLA windows, generated by the profiler."
  default     = {}
}
